version: '2'

services:
  yoothubapi:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.release
      args:
      - CONTAINER_PORT=${YOOTHUBAPI_PORT}
      - SERVER_URLS=http://*:${YOOTHUBAPI_PORT}
    ports:
    - "${HOST_PORT}:${YOOTHUBAPI_PORT}"
